# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

steps:
- script: |
    mkdir sync
    cd sync
    git clone https://github.com/INTMIN/react-learn-file.git
    
    cd react-learn-file
    git remote add azure  https://MINTEST:vehyol3vc2ceadekm3a76qvtyfwof3x7u4emnkeg6wmsfqvwxlia@dev.azure.com/MINTEXT/mintext.visualstudio.com/react-learn/_git/react-learn
    git branch -D $(master)
    git checkout -b $(master)
        
    git push -d azure $(master)
    git push -u azure $(master) --force
    displayName: 'add code'