# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
# steps:
# - uses: azure/webapps-deploy@v2
#   with:
#     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}


steps:

- script: |
    mkdir sync
    cd sync
    
    # git clone --bare https://mintext.visualstudio.com/react-learn-file/_git/react-learn-file
    
    git clone https://github.com/INTMIN/react-learn-file.git
    cd react-learn-file
    git remote add azure  https://MINTEXT:vehyol3vc2ceadekm3a76qvtyfwof3x7u4emnkeg6wmsfqvwxlia@dev.azure.com/MINTEXT/mintext.visualstudio.com/react-learn-file/_git/react-learn-file
   
    
    # git remote add --mirror=fetch upstream https://github.com/INTMIN/react-learn-file.git
    # git fetch upstream --tags
    # git push origin --all

    # git branch -D test
    git checkout -b test
        
    git push -d azure master
    git push -u azure master --force
  
  displayName: 'add code'
